Revert "tools: upgrade patcher.py"
This reverts commit c18c5167e2ac087f6f241f4c24a951ac7dce76d5.

That commit causes an error like this when running gclient hooks:

Apply boringssl.patch in C:\nwjs\src\third_party\boringssl\src
... failed to apply:
        error: git apply: bad git-diff - expected /dev/null on line 19
-------------------------------------------------------------------------------
!!!! ERROR: This patch failed to apply. Your build will not be correct.
-------------------------------------------------------------------------------